### ISSUE TITLE
Bucle en guardarArchivo - toArray()

### ISSUE THREAD

**Issue by daiant** [SHEKK0/ClaseDiccionario#12]
Al darle a guardar archivo se queda en bucle y eso que ya lo habíamos visto. 
Del debugger saco que es culpa de NodoPalabra.getNext(); 
No sé yo lo pongo aquí. 
Tengo sueño

**Comment by SHEKK0** [comment]
En el toArray, cuando creas el array resultado deberia ser,creo, un array de longitud this.size y no  this.size +1. Mira a ver si es eso

**Comment by daiant** [comment]
No, eso lo puse luego, da igual el tamaño del array porque hay un bucle infinito

**Comment by ToniApps** [comment]
En que branch? @daiant

**Comment by daiant** [comment]
Daiant_PI

**Comment by daiant** [comment]
La verdad es que ni idea de qué he hecho para cambiarlo, pero ya funciona ok.
