### ISSUE TITLE
La lectura del archivo de datos no debe estar en la clase Palabra

### ISSUE THREAD

**Issue by ToniApps** [SHEKK0/ClaseDiccionario#5]
La lectura del archivo debe estar en la API no en la clase Palabra

**Comment by SHEKK0** [comment]
Es que si lo metes en la clase palabra es mas facil de entender a mi parecer, así no haces todo el lio en un mismo sitio

**Comment by ToniApps** [comment]
Pero es que así no se hace 😅 si es una api hay que leer los datos desde ella

**Comment by SHEKK0** [comment]
pues cambialo
