### ISSUE TITLE
Diccionario.java - primeraPalabra

### ISSUE THREAD

**Issue by daiant** [SHEKK0/ClaseDiccionario#7]
Para que lo necesitamos si podemos acceder a todas las posiciones, que son arrays?

**Comment by ToniApps** [comment]
??? explíquese señor

**Comment by daiant** [comment]
Tenemos una variable llamada primerapalabra que accede a la primera instancia de palabras. 
Pero eso solo es util si tenemos listas de enlaces, pienso yo, porque como palabras es un array podemos acceder a cualquier posicion siempre que queramos.

**Comment by ToniApps** [comment]
Arreglado
